/*
 * Copyright (c) 2024 Michael Hope
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_CH5XX_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_CH5XX_CLOCKS_H_

#define CH5XX_CLOCK_CONFIG(reg, bit) ((reg << 4) | (bit))

/* R8_SLP_CLK_OFF0 */
#define CH5XX_CLOCK_USART1 CH5XX_CLOCK_CONFIG(0, 4)
#define CH5XX_CLOCK_CMP    CH5XX_CLOCK_CONFIG(0, 1)
#define CH5XX_CLOCK_TIMER  CH5XX_CLOCK_CONFIG(0, 0)

/* R8_SLP_CLK_OFF1 */
#define CH5XX_CLOCK_BLE  CH5XX_CLOCK_CONFIG(1, 7)
#define CH5XX_CLOCK_USB  CH5XX_CLOCK_CONFIG(1, 4)
#define CH5XX_CLOCK_I2C  CH5XX_CLOCK_CONFIG(1, 3)
#define CH5XX_CLOCK_PWM  CH5XX_CLOCK_CONFIG(1, 2)
#define CH5XX_CLOCK_AESC CH5XX_CLOCK_CONFIG(1, 1)
#define CH5XX_CLOCK_SPI  CH5XX_CLOCK_CONFIG(1, 0)

/* R8_SLP_CLK_OFF1 */
#define CH5XX_CLOCK_FLASH_HCLK CH5XX_CLOCK_CONFIG(2, 4)
#define CH5XX_CLOCK_DEBUG      CH5XX_CLOCK_CONFIG(2, 1)
#define CH5XX_CLOCK_XROM       CH5XX_CLOCK_CONFIG(2, 0)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_CH5XX_CLOCKS_H_ */
